# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: qunmi
    role: Maintain
  - member: haltonhuo
    role: Maintain
  - member: daimingpan
    role: Write
  - team: edgechinaawmdev
    role: Write
  - member: ericwa
    role: Write
  - member: guwa
    role: Write
  - member: haoji
    role: Write
  - member: hezhan
    role: Write
  - member: linguo2
    role: Write
  - member: qi.yang
    role: Write
  - member: ranyu
    role: Write
  - member: shulianghan
    role: Write
  - member: tandavid
    role: Write
  - member: yananzhao
    role: Write
  - member: ygu
    role: Write
  - member: yuhaibo
    role: Write
  - member: yujiang
    role: Write
  - member: zengchanliu
    role: Write
  - member: zhuangxu
    role: Write
